--CREAR NUESTRO DATAWAREHOUSE

CREATE DATABASE DWH_VENTA
GO

USE DWH_VENTA
GO

--CREACION DE LAS TABLAS DE LA BASE DE DATOS PARAMETROS

CREATE TABLE DIM_VENDEDOR (
	--VENDEDOR_KEY INT IDENTITY(1,1) NOT NULL,
	COD_VENDEDOR CHAR (10) PRIMARY KEY,
	NOMBRE_COMPLETO_VENDEDOR VARCHAR(65) NOT NULL,
	--PRIMARY KEY(VENDEDOR_KEY)
)
GO

CREATE TABLE DIM_PRODUCTO(
	--PRODUCTO_KEY int IDENTITY(1,1) NOT NULL,
	COD_PRODUCTO char(12) PRIMARY KEY,
	NOMBRE_PROD varchar(150) NOT NULL,
	CATEGORIA_PROD varchar(50) NOT NULL,
	SUBCATEGORIA_PROD varchar(50) NOT NULL,
	PRECIO_UNITARIO decimal(8, 2) NOT NULL,
	--PRIMARY KEY(PRODUCTO_KEY)
)
GO

CREATE TABLE FACT_VENTA (
	--BANCO_FK INT NOT NULL,
	TIPO_DOCUMENTO CHAR(2) NOT NULL,
	FECHA_VENTA DATE NOT NULL,
	PRECIO_UNITARIO decimal(8, 2) NOT NULL,
	CANTIDAD INT NOT NULL,
	--NUM_VENTA VARCHAR(13) NOT NULL,
	DNI VARCHAR(11) NOT NULL,
	COD_VENDEDOR CHAR(10) FOREIGN KEY REFERENCES DIM_VENDEDOR(COD_VENDEDOR),
	COD_PRODUCTO CHAR(12) FOREIGN KEY REFERENCES DIM_PRODUCTO(COD_PRODUCTO)
)
GO





