SELECT *
FROM DWH_VENTA..DIM_VENDEDOR

--INGESTAMOS DIM_VENDEDOR--
INSERT INTO DWH_VENTA..DIM_VENDEDOR
SELECT A.cod_vendedor, A.apellido_vendedor+', '+nombre_vendedor
FROM SUPERMAYORISTA..VENDEDOR A

SELECT *
FROM DWH_VENTA..DIM_PRODUCTO

--INGESTAMOS DIM_PRODUCTO--
INSERT INTO DWH_VENTA..DIM_PRODUCTO
SELECT  A.cod_producto, A.nombre_producto, A.categoria_producto, A.subcategoria_producto,
		B.precio_unitario
FROM SUPERMAYORISTA..PRODUCTO A
JOIN (SELECT A.cod_producto, A.precio_unitario, COUNT(1) as 'CANTIDAD'
FROM SUPERMAYORISTA..DETALLE_VENTA A
GROUP BY A.cod_producto,A.precio_unitario) B ON A.cod_producto = B.cod_producto

--302060--
--INGESTAMOS FACT_VENTA--
INSERT INTO DWH_VENTA..FACT_VENTA
SELECT  LEFT(B.nombre_tipo_documento,1), 
		B.fecha_venta, 
		A.precio_unitario, 
		A.cantidad, 
		B.dni_cliente, 
	--	B.vendedor,
		C.cod_vendedor, 
		A.cod_producto
FROM SUPERMAYORISTA..DETALLE_VENTA A
LEFT JOIN SUPERMAYORISTA..VENTA B ON A.cod_documento = B.cod_documento
LEFT JOIN SUPERMAYORISTA..VENDEDOR C ON B.vendedor = C.apellido_vendedor+', '+nombre_vendedor

SELECT * FROM DWH_VENTA..FACT_VENTA
SELECT * FROM DWH_VENTA..DIM_PRODUCTO
SELECT * FROM DWH_VENTA..DIM_VENDEDOR

DELETE FROM DWH_VENTA..DIM_PRODUCTO
DELETE FROM DWH_VENTA..DIM_VENDEDOR


/*SELECT DISTINCT A.cod_producto, A.nombre_producto, A.categoria_producto, A.subcategoria_producto,
		B.precio_unitario
FROM SUPERMAYORISTA..PRODUCTO A
LEFT JOIN SUPERMAYORISTA..DETALLE_VENTA B ON A.cod_producto = B.cod_producto*/




SELECT A.*
FROM SUPERMAYORISTA..PRODUCTO A

SELECT A.cod_producto, COUNT(1)
FROM SUPERMAYORISTA..DETALLE_VENTA A
GROUP BY A.cod_producto

SELECT A.*
FROM SUPERMAYORISTA..VENTA A

SELECT A.*
FROM SUPERMAYORISTA..VENDEDOR A

SELECT A.*
FROM SUPERMAYORISTA..TIPO_DOCUMENTO A

